language: bash

services:
  - docker

env:
  matrix:
  - PROTOC_VERSION=3.11.2
  
before_install:
  - docker build -t automatizer/gradle-protoc:$PROTOC_VERSION .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push automatizer/gradle-protoc:$PROTOC_VERSION
